version: '3.6'
services:
  lunie-script-runner:
    image: lunie-script-runner:latest
    container_name: lunie-script-runner
    restart: unless-stopped
    secrets:
    - HASURA_ADMIN_KEY
    volumes:
    - /logs:/logs
    - caches:/api/caches
    networks:
       - general
    logging:
      driver: loki
      options:
        loki-url: "http://api_key:${LOKI_API_KEY}@monitoring.lunie.io:3100/loki/api/v1/push"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2.5G
    environment:
      - HASURA_URL=$HASURA_URL
      - HASURA_ADMIN_KEY=$HASURA_ADMIN_KEY
      - SENTRY_DSN=$SENTRY_DSN
      - AUTHENTICATION_TOKEN=$AUTHENTICATION_TOKEN
    ports:
    - "9000:9000"
secrets:
  HASURA_ADMIN_KEY:
    external: true
volumes:  
  caches:
networks:
  general:

